### ISSUE TITLE
UTF-8 Encoding

### ISSUE THREAD

**Issue by Freddyvdh** [UweKeim/ZetaResourceEditor#24]
Hi,

first of all, thanks for the great tool!

I'm working in my project with SVN, so I recognized after changing a neutral language file, that the german file had changes too, but only in the encoding.

I'm using VS 2013 and the default encoding seems to be UTF-8 BOM.

In the code I found that the StreamWriter is intialized with Utf8Encoding(false)(RuntimeBusinessLogic/BL/DataProcessing.cs, Line 128).
Is there is reason why it is Utf8Encoding(false) and not Utf8Encoding(true), or you never thought about it?

I tried to build the Source, but the solution can't be build with VS 2013

Thanks,
Freddy

**Comment by UweKeim** [comment]
Just "blame"d through my SVN to found no special remarks.

Probably "never thought about it". 

I'll change now.

**Comment by UweKeim** [comment]
Done and published a new setup.exe.

I've kept the version number to not force all the users to download an update. Hope this is OK.

**Comment by Freddyvdh** [comment]
It's working!
Thanks for the quick fix.

PS: The DevExpress DLLs are still missing ;)
